FROM maven:3.6-jdk-11 as builder


COPY . /app
WORKDIR /app


RUN mvn package -X


FROM eclipse-temurin:17-jre
WORKDIR /app


COPY --from=builder /app/target/SocialMediaApp-0.0.1-SNAPSHOT.jar app.jar


EXPOSE 8080


ENTRYPOINT ["java", "-jar", "app.jar"]